
version: "3.9"
services:
  launch_service:
    build: 
      context: .
      dockerfile: ./dockerfile-server
    environment:
      GRAPHQL_URL: "https://api.spacex.land/graphql/"
      SERVER_PORT: 50051
    ports:
      - "50051:50051"

  launch_client:
    build: 
      context: .
      dockerfile: ./dockerfile-client
    environment:
      LAUNCH_ADDRESS: "launch_service:50051" 
    ports:
      - "4040:4040"
    depends_on:
        - launch_service