// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.4
// source: launch_grpc/launch.proto

package launch

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Launch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsTentative   bool   `protobuf:"varint,2,opt,name=is_tentative,json=isTentative,proto3" json:"is_tentative,omitempty"`
	LaunchSuccess bool   `protobuf:"varint,3,opt,name=launch_success,json=launchSuccess,proto3" json:"launch_success,omitempty"`
	Upcoming      bool   `protobuf:"varint,4,opt,name=upcoming,proto3" json:"upcoming,omitempty"`
	MissionName   string `protobuf:"bytes,5,opt,name=mission_name,json=missionName,proto3" json:"mission_name,omitempty"`
}

func (x *Launch) Reset() {
	*x = Launch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_grpc_launch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Launch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Launch) ProtoMessage() {}

func (x *Launch) ProtoReflect() protoreflect.Message {
	mi := &file_launch_grpc_launch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Launch.ProtoReflect.Descriptor instead.
func (*Launch) Descriptor() ([]byte, []int) {
	return file_launch_grpc_launch_proto_rawDescGZIP(), []int{0}
}

func (x *Launch) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Launch) GetIsTentative() bool {
	if x != nil {
		return x.IsTentative
	}
	return false
}

func (x *Launch) GetLaunchSuccess() bool {
	if x != nil {
		return x.LaunchSuccess
	}
	return false
}

func (x *Launch) GetUpcoming() bool {
	if x != nil {
		return x.Upcoming
	}
	return false
}

func (x *Launch) GetMissionName() string {
	if x != nil {
		return x.MissionName
	}
	return ""
}

type GetLaunchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLaunchRequest) Reset() {
	*x = GetLaunchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_grpc_launch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLaunchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaunchRequest) ProtoMessage() {}

func (x *GetLaunchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_grpc_launch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaunchRequest.ProtoReflect.Descriptor instead.
func (*GetLaunchRequest) Descriptor() ([]byte, []int) {
	return file_launch_grpc_launch_proto_rawDescGZIP(), []int{1}
}

func (x *GetLaunchRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLaunchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Launch *Launch `protobuf:"bytes,1,opt,name=launch,proto3" json:"launch,omitempty"`
}

func (x *GetLaunchResponse) Reset() {
	*x = GetLaunchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_grpc_launch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLaunchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaunchResponse) ProtoMessage() {}

func (x *GetLaunchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_grpc_launch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaunchResponse.ProtoReflect.Descriptor instead.
func (*GetLaunchResponse) Descriptor() ([]byte, []int) {
	return file_launch_grpc_launch_proto_rawDescGZIP(), []int{2}
}

func (x *GetLaunchResponse) GetLaunch() *Launch {
	if x != nil {
		return x.Launch
	}
	return nil
}

type GetLaunchesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetLaunchesRequest) Reset() {
	*x = GetLaunchesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_grpc_launch_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLaunchesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaunchesRequest) ProtoMessage() {}

func (x *GetLaunchesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_launch_grpc_launch_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaunchesRequest.ProtoReflect.Descriptor instead.
func (*GetLaunchesRequest) Descriptor() ([]byte, []int) {
	return file_launch_grpc_launch_proto_rawDescGZIP(), []int{3}
}

type GetLaunchesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Launches []*Launch `protobuf:"bytes,1,rep,name=launches,proto3" json:"launches,omitempty"`
}

func (x *GetLaunchesResponse) Reset() {
	*x = GetLaunchesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_launch_grpc_launch_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLaunchesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLaunchesResponse) ProtoMessage() {}

func (x *GetLaunchesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_launch_grpc_launch_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLaunchesResponse.ProtoReflect.Descriptor instead.
func (*GetLaunchesResponse) Descriptor() ([]byte, []int) {
	return file_launch_grpc_launch_proto_rawDescGZIP(), []int{4}
}

func (x *GetLaunchesResponse) GetLaunches() []*Launch {
	if x != nil {
		return x.Launches
	}
	return nil
}

var File_launch_grpc_launch_proto protoreflect.FileDescriptor

var file_launch_grpc_launch_proto_rawDesc = []byte{
	0x0a, 0x18, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x61,
	0x75, 0x6e, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x06, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x74, 0x65, 0x6e, 0x74,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x54,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x76, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x6c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x5f, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x75, 0x70, 0x63, 0x6f, 0x6d, 0x69, 0x6e, 0x67, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x22,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x34, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x6c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x52, 0x06, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x08, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68,
	0x52, 0x08, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x32, 0x81, 0x01, 0x0a, 0x0d, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x09,
	0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x12, 0x11, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65,
	0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x75, 0x6e,
	0x63, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x33,
	0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x69, 0x72,
	0x69, 0x73, 0x68, 0x67, 0x34, 0x74, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d, 0x74, 0x65, 0x73, 0x74,
	0x2f, 0x6c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x6c, 0x61, 0x75,
	0x6e, 0x63, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_launch_grpc_launch_proto_rawDescOnce sync.Once
	file_launch_grpc_launch_proto_rawDescData = file_launch_grpc_launch_proto_rawDesc
)

func file_launch_grpc_launch_proto_rawDescGZIP() []byte {
	file_launch_grpc_launch_proto_rawDescOnce.Do(func() {
		file_launch_grpc_launch_proto_rawDescData = protoimpl.X.CompressGZIP(file_launch_grpc_launch_proto_rawDescData)
	})
	return file_launch_grpc_launch_proto_rawDescData
}

var file_launch_grpc_launch_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_launch_grpc_launch_proto_goTypes = []interface{}{
	(*Launch)(nil),              // 0: Launch
	(*GetLaunchRequest)(nil),    // 1: GetLaunchRequest
	(*GetLaunchResponse)(nil),   // 2: GetLaunchResponse
	(*GetLaunchesRequest)(nil),  // 3: GetLaunchesRequest
	(*GetLaunchesResponse)(nil), // 4: GetLaunchesResponse
}
var file_launch_grpc_launch_proto_depIdxs = []int32{
	0, // 0: GetLaunchResponse.launch:type_name -> Launch
	0, // 1: GetLaunchesResponse.launches:type_name -> Launch
	1, // 2: LaunchService.GetLaunch:input_type -> GetLaunchRequest
	3, // 3: LaunchService.GetLaunches:input_type -> GetLaunchesRequest
	2, // 4: LaunchService.GetLaunch:output_type -> GetLaunchResponse
	4, // 5: LaunchService.GetLaunches:output_type -> GetLaunchesResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_launch_grpc_launch_proto_init() }
func file_launch_grpc_launch_proto_init() {
	if File_launch_grpc_launch_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_launch_grpc_launch_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Launch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_grpc_launch_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLaunchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_grpc_launch_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLaunchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_grpc_launch_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLaunchesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_launch_grpc_launch_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLaunchesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_launch_grpc_launch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_launch_grpc_launch_proto_goTypes,
		DependencyIndexes: file_launch_grpc_launch_proto_depIdxs,
		MessageInfos:      file_launch_grpc_launch_proto_msgTypes,
	}.Build()
	File_launch_grpc_launch_proto = out.File
	file_launch_grpc_launch_proto_rawDesc = nil
	file_launch_grpc_launch_proto_goTypes = nil
	file_launch_grpc_launch_proto_depIdxs = nil
}
